import { ChangeDetectionStrategy, Component, computed, input, model, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import { AppIcon } from '../app-icon/app-icon';

export type UploadFileItem = {
  file: File;
  name: string;
};

@Component({
  selector: 'app-file-upload-list',
  imports: [AppIcon, TranslatePipe],
  templateUrl: './file-upload-list.html',
  styleUrl: './file-upload-list.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileUploadList {
  private static nextId = 0;
  public readonly inputId = `file-upload-${FileUploadList.nextId++}`;

  /**
   * Two-way bindable list of upload file items with their names.
   */
  public readonly items = model<UploadFileItem[]>([]);

  /**
   * Accepted file extensions/MIME types (e.g. '.gpx', '.fit,.gpx,.tcx,.zip').
   */
  public readonly accept = input<string>('*');

  /**
   * Whether to allow multiple file selection.
   */
  public readonly multiple = input<boolean>(true);

  /**
   * Disabled state for file picker and inputs.
   */
  public readonly disabled = input<boolean>(false);

  /**
   * Label for the file input.
   */
  public readonly label = input<string>('File');

  /**
   * Help text displayed beneath the file input.
   */
  public readonly helpText = input<string | null>(null);

  /**
   * If true (e.g. for workouts), the name can be auto-generated by the backend
   * and is optional to edit (defaults to empty).
   * If false (e.g. for route segments), the name is pre-populated with the file base name.
   */
  public readonly optionalName = input<boolean>(false);

  /**
   * Label for the name input field.
   */
  public readonly nameLabel = input<string>('Name');

  /**
   * Custom placeholder override for the name input.
   */
  public readonly namePlaceholder = input<string | null>(null);

  /**
   * Emitted whenever the list of items or their names change.
   */
  public readonly filesChanged = output<UploadFileItem[]>();

  /**
   * Emitted when a file item is removed.
   */
  public readonly fileRemoved = output<{ item: UploadFileItem; index: number }>();

  public readonly effectivePlaceholder = computed(() => {
    const custom = this.namePlaceholder();
    if (custom) {
      return custom;
    }

    return 'Name';
  });

  public onFilesSelected(event: Event): void {
    const inputEl = event.target as HTMLInputElement;
    if (!inputEl.files || inputEl.files.length === 0) {
      return;
    }

    const newFiles = Array.from(inputEl.files);
    const newItems: UploadFileItem[] = newFiles.map((file) => {
      let defaultName = '';
      if (!this.optionalName()) {
        defaultName = file.name.replace(/\.[^/.]+$/, '');
      }
      return { file, name: defaultName };
    });

    const updated = this.multiple() ? [...this.items(), ...newItems] : newItems;
    this.items.set(updated);
    this.filesChanged.emit(updated);

    // Reset file input value so re-selecting same file works
    inputEl.value = '';
  }

  public updateItemName(index: number, name: string): void {
    const current = [...this.items()];
    if (index >= 0 && index < current.length) {
      current[index] = { ...current[index], name };
      this.items.set(current);
      this.filesChanged.emit(current);
    }
  }

  public removeItem(index: number): void {
    const current = [...this.items()];
    if (index >= 0 && index < current.length) {
      const [removed] = current.splice(index, 1);
      this.items.set(current);
      this.fileRemoved.emit({ item: removed, index });
      this.filesChanged.emit(current);
    }
  }

  public formatFileSize(bytes: number): string {
    if (bytes < 1024) {
      return `${bytes} B`;
    }
    if (bytes < 1024 * 1024) {
      return `${(bytes / 1024).toFixed(1)} KB`;
    }
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }
}
