// Code generated by generate-workout-types; DO NOT EDIT.
package model

import "strings"

const (
	WorkoutTypeAll                   WorkoutType = "all"
	WorkoutTypeAlpineSkiing          WorkoutType = "alpine_skiing"
	WorkoutTypeAmericanFootball      WorkoutType = "american_football"
	WorkoutTypeArchery               WorkoutType = "archery"
	WorkoutTypeBaseball              WorkoutType = "baseball"
	WorkoutTypeBasketball            WorkoutType = "basketball"
	WorkoutTypeBoating               WorkoutType = "boating"
	WorkoutTypeBoxing                WorkoutType = "boxing"
	WorkoutTypeCanoeing              WorkoutType = "canoeing"
	WorkoutTypeCricket               WorkoutType = "cricket"
	WorkoutTypeCrossCountrySkiing    WorkoutType = "cross_country_skiing"
	WorkoutTypeCycling               WorkoutType = "cycling"
	WorkoutTypeDance                 WorkoutType = "dance"
	WorkoutTypeDiscGolf              WorkoutType = "disc_golf"
	WorkoutTypeDiving                WorkoutType = "diving"
	WorkoutTypeDriving               WorkoutType = "driving"
	WorkoutTypeEBiking               WorkoutType = "e_biking"
	WorkoutTypeExpedition            WorkoutType = "expedition"
	WorkoutTypeFishing               WorkoutType = "fishing"
	WorkoutTypeFitnessEquipment      WorkoutType = "fitness_equipment"
	WorkoutTypeFloorClimbing         WorkoutType = "floor_climbing"
	WorkoutTypeFlying                WorkoutType = "flying"
	WorkoutTypeGeneric               WorkoutType = "generic"
	WorkoutTypeGeocaching            WorkoutType = "geocaching"
	WorkoutTypeGolf                  WorkoutType = "golf"
	WorkoutTypeGrinding              WorkoutType = "grinding"
	WorkoutTypeHangGliding           WorkoutType = "hang_gliding"
	WorkoutTypeHiit                  WorkoutType = "hiit"
	WorkoutTypeHiking                WorkoutType = "hiking"
	WorkoutTypeHockey                WorkoutType = "hockey"
	WorkoutTypeHorsebackRiding       WorkoutType = "horseback_riding"
	WorkoutTypeHunting               WorkoutType = "hunting"
	WorkoutTypeIceSkating            WorkoutType = "ice_skating"
	WorkoutTypeIndoorHandCycling     WorkoutType = "indoor_hand_cycling"
	WorkoutTypeInlineSkating         WorkoutType = "inline_skating"
	WorkoutTypeJumpRope              WorkoutType = "jump_rope"
	WorkoutTypeJumpmaster            WorkoutType = "jumpmaster"
	WorkoutTypeKayaking              WorkoutType = "kayaking"
	WorkoutTypeKitesurfing           WorkoutType = "kitesurfing"
	WorkoutTypeLacrosse              WorkoutType = "lacrosse"
	WorkoutTypeMeditation            WorkoutType = "meditation"
	WorkoutTypeMixedMartialArts      WorkoutType = "mixed_martial_arts"
	WorkoutTypeMobility              WorkoutType = "mobility"
	WorkoutTypeMotorSports           WorkoutType = "motor_sports"
	WorkoutTypeMotorcycling          WorkoutType = "motorcycling"
	WorkoutTypeMountaineering        WorkoutType = "mountaineering"
	WorkoutTypeMultisport            WorkoutType = "multisport"
	WorkoutTypeObstacle              WorkoutType = "obstacle"
	WorkoutTypeOverland              WorkoutType = "overland"
	WorkoutTypePaddling              WorkoutType = "paddling"
	WorkoutTypeParaSport             WorkoutType = "para_sport"
	WorkoutTypeRacket                WorkoutType = "racket"
	WorkoutTypeRafting               WorkoutType = "rafting"
	WorkoutTypeRockClimbing          WorkoutType = "rock_climbing"
	WorkoutTypeRowing                WorkoutType = "rowing"
	WorkoutTypeRugby                 WorkoutType = "rugby"
	WorkoutTypeRunning               WorkoutType = "running"
	WorkoutTypeSailing               WorkoutType = "sailing"
	WorkoutTypeShooting              WorkoutType = "shooting"
	WorkoutTypeSkyDiving             WorkoutType = "sky_diving"
	WorkoutTypeSnorkeling            WorkoutType = "snorkeling"
	WorkoutTypeSnowboarding          WorkoutType = "snowboarding"
	WorkoutTypeSnowmobiling          WorkoutType = "snowmobiling"
	WorkoutTypeSnowshoeing           WorkoutType = "snowshoeing"
	WorkoutTypeSoccer                WorkoutType = "soccer"
	WorkoutTypeStandUpPaddleboarding WorkoutType = "stand_up_paddleboarding"
	WorkoutTypeSurfing               WorkoutType = "surfing"
	WorkoutTypeSwimming              WorkoutType = "swimming"
	WorkoutTypeTactical              WorkoutType = "tactical"
	WorkoutTypeTeamSport             WorkoutType = "team_sport"
	WorkoutTypeTennis                WorkoutType = "tennis"
	WorkoutTypeTraining              WorkoutType = "training"
	WorkoutTypeTransition            WorkoutType = "transition"
	WorkoutTypeTrollingMotor         WorkoutType = "trolling_motor"
	WorkoutTypeUltra                 WorkoutType = "ultra"
	WorkoutTypeVideoGaming           WorkoutType = "video_gaming"
	WorkoutTypeVirtualActivity       WorkoutType = "virtual_activity"
	WorkoutTypeVolleyball            WorkoutType = "volleyball"
	WorkoutTypeWakeboarding          WorkoutType = "wakeboarding"
	WorkoutTypeWakesurfing           WorkoutType = "wakesurfing"
	WorkoutTypeWalking               WorkoutType = "walking"
	WorkoutTypeWaterSkiing           WorkoutType = "water_skiing"
	WorkoutTypeWaterSport            WorkoutType = "water_sport"
	WorkoutTypeWaterTubing           WorkoutType = "water_tubing"
	WorkoutTypeWheelchairPushRun     WorkoutType = "wheelchair_push_run"
	WorkoutTypeWheelchairPushWalk    WorkoutType = "wheelchair_push_walk"
	WorkoutTypeWindsurfing           WorkoutType = "windsurfing"
	WorkoutTypeWinterSport           WorkoutType = "winter_sport"
)

var workoutTypeConfigs = map[WorkoutType]WorkoutTypeConfiguration{
	WorkoutTypeAll:                   {Location: true, Distance: true, Repetition: true, Weight: true, ExcludeFromRecords: false},
	WorkoutTypeAlpineSkiing:          {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeAmericanFootball:      {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeArchery:               {Location: true, Distance: true, Repetition: true, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeBaseball:              {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeBasketball:            {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeBoating:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeBoxing:                {Location: true, Distance: false, Repetition: true, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeCanoeing:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeCricket:               {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeCrossCountrySkiing:    {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeCycling:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeDance:                 {Location: false, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeDiscGolf:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeDiving:                {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeDriving:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeEBiking:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeExpedition:            {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeFishing:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeFitnessEquipment:      {Location: false, Distance: false, Repetition: true, Weight: true, ExcludeFromRecords: false},
	WorkoutTypeFloorClimbing:         {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeFlying:                {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeGeneric:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeGeocaching:            {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeGolf:                  {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeGrinding:              {Location: true, Distance: false, Repetition: true, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeHangGliding:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeHiit:                  {Location: false, Distance: false, Repetition: true, Weight: true, ExcludeFromRecords: false},
	WorkoutTypeHiking:                {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeHockey:                {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeHorsebackRiding:       {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeHunting:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeIceSkating:            {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeIndoorHandCycling:     {Location: false, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: true},
	WorkoutTypeInlineSkating:         {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeJumpRope:              {Location: false, Distance: false, Repetition: true, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeJumpmaster:            {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeKayaking:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeKitesurfing:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeLacrosse:              {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeMeditation:            {Location: false, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeMixedMartialArts:      {Location: true, Distance: false, Repetition: true, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeMobility:              {Location: false, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeMotorSports:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeMotorcycling:          {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeMountaineering:        {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeMultisport:            {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeObstacle:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeOverland:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypePaddling:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeParaSport:             {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeRacket:                {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeRafting:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeRockClimbing:          {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeRowing:                {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeRugby:                 {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeRunning:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSailing:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeShooting:              {Location: true, Distance: true, Repetition: true, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSkyDiving:             {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSnorkeling:            {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSnowboarding:          {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSnowmobiling:          {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSnowshoeing:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSoccer:                {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeStandUpPaddleboarding: {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSurfing:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeSwimming:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeTactical:              {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeTeamSport:             {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeTennis:                {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeTraining:              {Location: false, Distance: false, Repetition: true, Weight: true, ExcludeFromRecords: false},
	WorkoutTypeTransition:            {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeTrollingMotor:         {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeUltra:                 {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeVideoGaming:           {Location: false, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeVirtualActivity:       {Location: false, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: true},
	WorkoutTypeVolleyball:            {Location: true, Distance: false, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWakeboarding:          {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWakesurfing:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWalking:               {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWaterSkiing:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWaterSport:            {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWaterTubing:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWheelchairPushRun:     {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWheelchairPushWalk:    {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWindsurfing:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
	WorkoutTypeWinterSport:           {Location: true, Distance: true, Repetition: false, Weight: false, ExcludeFromRecords: false},
}

var excludedRecordSubTypes = map[string]bool{
	"indoor_cycling":   true,
	"indoor_running":   true,
	"spin":             true,
	"treadmill":        true,
	"virtual_activity": true,
}

func (wt WorkoutType) ExcludeFromRecords() bool {
	if cfg, ok := workoutTypeConfigs[wt]; ok {
		return cfg.ExcludeFromRecords
	}
	return false
}

func IsSubTypeExcludedFromRecords(subType string) bool {
	return excludedRecordSubTypes[strings.ToLower(strings.TrimSpace(subType))]
}

func ExcludedRecordSubTypes() []string {
	return []string{
		"indoor_cycling",
		"indoor_running",
		"spin",
		"treadmill",
		"virtual_activity",
	}
}

func ExcludedRecordWorkoutTypes() []WorkoutType {
	return []WorkoutType{
		WorkoutTypeIndoorHandCycling,
		WorkoutTypeVirtualActivity,
	}
}

func ParseWorkoutType(s string) (WorkoutType, bool) {
	switch WorkoutType(s) {
	case WorkoutTypeAll:
		return WorkoutTypeAll, true
	case WorkoutTypeAlpineSkiing:
		return WorkoutTypeAlpineSkiing, true
	case WorkoutTypeAmericanFootball:
		return WorkoutTypeAmericanFootball, true
	case WorkoutTypeArchery:
		return WorkoutTypeArchery, true
	case WorkoutTypeBaseball:
		return WorkoutTypeBaseball, true
	case WorkoutTypeBasketball:
		return WorkoutTypeBasketball, true
	case WorkoutTypeBoating:
		return WorkoutTypeBoating, true
	case WorkoutTypeBoxing:
		return WorkoutTypeBoxing, true
	case WorkoutTypeCanoeing:
		return WorkoutTypeCanoeing, true
	case WorkoutTypeCricket:
		return WorkoutTypeCricket, true
	case WorkoutTypeCrossCountrySkiing:
		return WorkoutTypeCrossCountrySkiing, true
	case WorkoutTypeCycling:
		return WorkoutTypeCycling, true
	case WorkoutTypeDance:
		return WorkoutTypeDance, true
	case WorkoutTypeDiscGolf:
		return WorkoutTypeDiscGolf, true
	case WorkoutTypeDiving:
		return WorkoutTypeDiving, true
	case WorkoutTypeDriving:
		return WorkoutTypeDriving, true
	case WorkoutTypeEBiking:
		return WorkoutTypeEBiking, true
	case WorkoutTypeExpedition:
		return WorkoutTypeExpedition, true
	case WorkoutTypeFishing:
		return WorkoutTypeFishing, true
	case WorkoutTypeFitnessEquipment:
		return WorkoutTypeFitnessEquipment, true
	case WorkoutTypeFloorClimbing:
		return WorkoutTypeFloorClimbing, true
	case WorkoutTypeFlying:
		return WorkoutTypeFlying, true
	case WorkoutTypeGeneric:
		return WorkoutTypeGeneric, true
	case WorkoutTypeGeocaching:
		return WorkoutTypeGeocaching, true
	case WorkoutTypeGolf:
		return WorkoutTypeGolf, true
	case WorkoutTypeGrinding:
		return WorkoutTypeGrinding, true
	case WorkoutTypeHangGliding:
		return WorkoutTypeHangGliding, true
	case WorkoutTypeHiit:
		return WorkoutTypeHiit, true
	case WorkoutTypeHiking:
		return WorkoutTypeHiking, true
	case WorkoutTypeHockey:
		return WorkoutTypeHockey, true
	case WorkoutTypeHorsebackRiding:
		return WorkoutTypeHorsebackRiding, true
	case WorkoutTypeHunting:
		return WorkoutTypeHunting, true
	case WorkoutTypeIceSkating:
		return WorkoutTypeIceSkating, true
	case WorkoutTypeIndoorHandCycling:
		return WorkoutTypeIndoorHandCycling, true
	case WorkoutTypeInlineSkating:
		return WorkoutTypeInlineSkating, true
	case WorkoutTypeJumpRope:
		return WorkoutTypeJumpRope, true
	case WorkoutTypeJumpmaster:
		return WorkoutTypeJumpmaster, true
	case WorkoutTypeKayaking:
		return WorkoutTypeKayaking, true
	case WorkoutTypeKitesurfing:
		return WorkoutTypeKitesurfing, true
	case WorkoutTypeLacrosse:
		return WorkoutTypeLacrosse, true
	case WorkoutTypeMeditation:
		return WorkoutTypeMeditation, true
	case WorkoutTypeMixedMartialArts:
		return WorkoutTypeMixedMartialArts, true
	case WorkoutTypeMobility:
		return WorkoutTypeMobility, true
	case WorkoutTypeMotorSports:
		return WorkoutTypeMotorSports, true
	case WorkoutTypeMotorcycling:
		return WorkoutTypeMotorcycling, true
	case WorkoutTypeMountaineering:
		return WorkoutTypeMountaineering, true
	case WorkoutTypeMultisport:
		return WorkoutTypeMultisport, true
	case WorkoutTypeObstacle:
		return WorkoutTypeObstacle, true
	case WorkoutTypeOverland:
		return WorkoutTypeOverland, true
	case WorkoutTypePaddling:
		return WorkoutTypePaddling, true
	case WorkoutTypeParaSport:
		return WorkoutTypeParaSport, true
	case WorkoutTypeRacket:
		return WorkoutTypeRacket, true
	case WorkoutTypeRafting:
		return WorkoutTypeRafting, true
	case WorkoutTypeRockClimbing:
		return WorkoutTypeRockClimbing, true
	case WorkoutTypeRowing:
		return WorkoutTypeRowing, true
	case WorkoutTypeRugby:
		return WorkoutTypeRugby, true
	case WorkoutTypeRunning:
		return WorkoutTypeRunning, true
	case WorkoutTypeSailing:
		return WorkoutTypeSailing, true
	case WorkoutTypeShooting:
		return WorkoutTypeShooting, true
	case WorkoutTypeSkyDiving:
		return WorkoutTypeSkyDiving, true
	case WorkoutTypeSnorkeling:
		return WorkoutTypeSnorkeling, true
	case WorkoutTypeSnowboarding:
		return WorkoutTypeSnowboarding, true
	case WorkoutTypeSnowmobiling:
		return WorkoutTypeSnowmobiling, true
	case WorkoutTypeSnowshoeing:
		return WorkoutTypeSnowshoeing, true
	case WorkoutTypeSoccer:
		return WorkoutTypeSoccer, true
	case WorkoutTypeStandUpPaddleboarding:
		return WorkoutTypeStandUpPaddleboarding, true
	case WorkoutTypeSurfing:
		return WorkoutTypeSurfing, true
	case WorkoutTypeSwimming:
		return WorkoutTypeSwimming, true
	case WorkoutTypeTactical:
		return WorkoutTypeTactical, true
	case WorkoutTypeTeamSport:
		return WorkoutTypeTeamSport, true
	case WorkoutTypeTennis:
		return WorkoutTypeTennis, true
	case WorkoutTypeTraining:
		return WorkoutTypeTraining, true
	case WorkoutTypeTransition:
		return WorkoutTypeTransition, true
	case WorkoutTypeTrollingMotor:
		return WorkoutTypeTrollingMotor, true
	case WorkoutTypeUltra:
		return WorkoutTypeUltra, true
	case WorkoutTypeVideoGaming:
		return WorkoutTypeVideoGaming, true
	case WorkoutTypeVirtualActivity:
		return WorkoutTypeVirtualActivity, true
	case WorkoutTypeVolleyball:
		return WorkoutTypeVolleyball, true
	case WorkoutTypeWakeboarding:
		return WorkoutTypeWakeboarding, true
	case WorkoutTypeWakesurfing:
		return WorkoutTypeWakesurfing, true
	case WorkoutTypeWalking:
		return WorkoutTypeWalking, true
	case WorkoutTypeWaterSkiing:
		return WorkoutTypeWaterSkiing, true
	case WorkoutTypeWaterSport:
		return WorkoutTypeWaterSport, true
	case WorkoutTypeWaterTubing:
		return WorkoutTypeWaterTubing, true
	case WorkoutTypeWheelchairPushRun:
		return WorkoutTypeWheelchairPushRun, true
	case WorkoutTypeWheelchairPushWalk:
		return WorkoutTypeWheelchairPushWalk, true
	case WorkoutTypeWindsurfing:
		return WorkoutTypeWindsurfing, true
	case WorkoutTypeWinterSport:
		return WorkoutTypeWinterSport, true
	default:
		return WorkoutTypeUnknown, false
	}
}
